// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBYivOwMsSivnPgHGiaVq_96tUDyIPjzE',
    appId: '1:1076994491261:web:602f73cc37904db42f8214',
    messagingSenderId: '1076994491261',
    projectId: 'resepmenu-14094',
    authDomain: 'resepmenu-14094.firebaseapp.com',
    storageBucket: 'resepmenu-14094.appspot.com',
    measurementId: 'G-BMG1TV9EGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIiL28j1mBPDY0qkFnQsYNN6vp29LYvdk',
    appId: '1:1076994491261:android:70f58d3f901206162f8214',
    messagingSenderId: '1076994491261',
    projectId: 'resepmenu-14094',
    storageBucket: 'resepmenu-14094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGuhK8l7rv3FdccSXIig94Y0_aWp6yPWo',
    appId: '1:1076994491261:ios:989f80cc104872df2f8214',
    messagingSenderId: '1076994491261',
    projectId: 'resepmenu-14094',
    storageBucket: 'resepmenu-14094.appspot.com',
    iosClientId: '1076994491261-a6oouofeto2qh83r4utegt261eo1lah5.apps.googleusercontent.com',
    iosBundleId: 'com.example.resep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGuhK8l7rv3FdccSXIig94Y0_aWp6yPWo',
    appId: '1:1076994491261:ios:b54e4abcaf84739c2f8214',
    messagingSenderId: '1076994491261',
    projectId: 'resepmenu-14094',
    storageBucket: 'resepmenu-14094.appspot.com',
    iosClientId: '1076994491261-94dd6esv9o7jm88hmdl0q3jq5ojv8m8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.resep.RunnerTests',
  );
}
